package channel

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	common2 "github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/relay/constant"
	"github.com/QuantumNous/new-api/relay/helper"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/setting/operation_setting"
	"github.com/QuantumNous/new-api/types"

	"github.com/bytedance/gopkg/util/gopool"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

func SetupApiRequestHeader(info *common.RelayInfo, c *gin.Context, req *http.Header) {
	if info.RelayMode == constant.RelayModeAudioTranscription || info.RelayMode == constant.RelayModeAudioTranslation {
		// multipart/form-data
	} else if info.RelayMode == constant.RelayModeRealtime {
		// websocket
	} else {
		req.Set("Content-Type", c.Request.Header.Get("Content-Type"))
		req.Set("Accept", c.Request.Header.Get("Accept"))
		if info.IsStream && c.Request.Header.Get("Accept") == "" {
			req.Set("Accept", "text/event-stream")
		}
	}
}

const clientHeaderPlaceholderPrefix = "{client_header:"

const (
	headerPassthroughAllKey        = "*"
	headerPassthroughRegexPrefix   = "re:"
	headerPassthroughRegexPrefixV2 = "regex:"
)

var passthroughSkipHeaderNamesLower = map[string]struct{}{
	// RFC 7230 hop-by-hop headers.
	"connection":          {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},

	"cookie": {},

	// Additional headers that should not be forwarded by name-matching passthrough rules.
	"host":            {},
	"content-length":  {},
	"accept-encoding": {},

	// Do not passthrough credentials by wildcard/regex.
	"authorization":  {},
	"x-api-key":      {},
	"x-goog-api-key": {},

	// WebSocket handshake headers are generated by the client/dialer.
	"sec-websocket-key":        {},
	"sec-websocket-version":    {},
	"sec-websocket-extensions": {},
}

var headerPassthroughRegexCache sync.Map // map[string]*regexp.Regexp

func getHeaderPassthroughRegex(pattern string) (*regexp.Regexp, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		return nil, errors.New("empty regex pattern")
	}
	if v, ok := headerPassthroughRegexCache.Load(pattern); ok {
		if re, ok := v.(*regexp.Regexp); ok {
			return re, nil
		}
		headerPassthroughRegexCache.Delete(pattern)
	}
	compiled, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	actual, _ := headerPassthroughRegexCache.LoadOrStore(pattern, compiled)
	if re, ok := actual.(*regexp.Regexp); ok {
		return re, nil
	}
	return compiled, nil
}

func IsHeaderPassthroughRuleKey(key string) bool {
	return isHeaderPassthroughRuleKey(key)
}
func isHeaderPassthroughRuleKey(key string) bool {
	key = strings.TrimSpace(key)
	if key == "" {
		return false
	}
	if key == headerPassthroughAllKey {
		return true
	}
	lower := strings.ToLower(key)
	return strings.HasPrefix(lower, headerPassthroughRegexPrefix) || strings.HasPrefix(lower, headerPassthroughRegexPrefixV2)
}

func shouldSkipPassthroughHeader(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)
	if _, ok := passthroughSkipHeaderNamesLower[lower]; ok {
		return true
	}
	return false
}

func applyHeaderOverridePlaceholders(template string, c *gin.Context, apiKey string) (string, bool, error) {
	trimmed := strings.TrimSpace(template)
	if strings.HasPrefix(trimmed, clientHeaderPlaceholderPrefix) {
		afterPrefix := trimmed[len(clientHeaderPlaceholderPrefix):]
		end := strings.Index(afterPrefix, "}")
		if end < 0 || end != len(afterPrefix)-1 {
			return "", false, fmt.Errorf("client_header placeholder must be the full value: %q", template)
		}

		name := strings.TrimSpace(afterPrefix[:end])
		if name == "" {
			return "", false, fmt.Errorf("client_header placeholder name is empty: %q", template)
		}
		if c == nil || c.Request == nil {
			return "", false, fmt.Errorf("missing request context for client_header placeholder")
		}
		clientHeaderValue := c.Request.Header.Get(name)
		if strings.TrimSpace(clientHeaderValue) == "" {
			return "", false, nil
		}
		// Do not interpolate {api_key} inside client-supplied content.
		return clientHeaderValue, true, nil
	}

	if strings.Contains(template, "{api_key}") {
		template = strings.ReplaceAll(template, "{api_key}", apiKey)
	}
	if strings.TrimSpace(template) == "" {
		return "", false, nil
	}
	return template, true, nil
}

// processHeaderOverride applies channel header overrides, with placeholder substitution.
// Supported placeholders:
//   - {api_key}: resolved to the channel API key
//   - {client_header:<name>}: resolved to the incoming request header value
//
// Header passthrough rules (keys only; values are ignored):
//   - "*": passthrough all incoming headers by name (excluding unsafe headers)
//   - "re:<regex>" / "regex:<regex>": passthrough headers whose names match the regex (Go regexp)
//
// Passthrough rules are applied first, then normal overrides are applied, so explicit overrides win.
func processHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	headerOverride := make(map[string]string)
	if info == nil {
		return headerOverride, nil
	}

	headerOverrideSource := common.GetEffectiveHeaderOverride(info)

	passAll := false
	var passthroughRegex []*regexp.Regexp
	if !info.IsChannelTest {
		for k := range headerOverrideSource {
			key := strings.TrimSpace(strings.ToLower(k))
			if key == "" {
				continue
			}
			if key == headerPassthroughAllKey {
				passAll = true
				continue
			}

			var pattern string
			switch {
			case strings.HasPrefix(key, headerPassthroughRegexPrefix):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefix):])
			case strings.HasPrefix(key, headerPassthroughRegexPrefixV2):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefixV2):])
			default:
				continue
			}

			if pattern == "" {
				return nil, types.NewError(fmt.Errorf("header passthrough regex pattern is empty: %q", k), types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			compiled, err := getHeaderPassthroughRegex(pattern)
			if err != nil {
				return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			passthroughRegex = append(passthroughRegex, compiled)
		}
	}

	if passAll || len(passthroughRegex) > 0 {
		if c == nil || c.Request == nil {
			return nil, types.NewError(fmt.Errorf("missing request context for header passthrough"), types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		for name := range c.Request.Header {
			if shouldSkipPassthroughHeader(name) {
				continue
			}
			if !passAll {
				matched := false
				for _, re := range passthroughRegex {
					if re.MatchString(name) {
						matched = true
						break
					}
				}
				if !matched {
					continue
				}
			}
			value := strings.TrimSpace(c.Request.Header.Get(name))
			if value == "" {
				continue
			}
			headerOverride[strings.ToLower(strings.TrimSpace(name))] = value
		}
	}

	for k, v := range headerOverrideSource {
		if isHeaderPassthroughRuleKey(k) {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(k))
		if key == "" {
			continue
		}

		str, ok := v.(string)
		if !ok {
			return nil, types.NewError(nil, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if info.IsChannelTest && strings.HasPrefix(strings.TrimSpace(str), clientHeaderPlaceholderPrefix) {
			continue
		}

		value, include, err := applyHeaderOverridePlaceholders(str, c, info.ApiKey)
		if err != nil {
			return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if !include {
			continue
		}

		headerOverride[key] = value
	}
	return headerOverride, nil
}

func ResolveHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	return processHeaderOverride(info, c)
}

func applyHeaderOverrideToRequest(req *http.Request, headerOverride map[string]string) {
	if req == nil {
		return
	}
	for key, value := range headerOverride {
		req.Header.Set(key, value)
		// set Host in req
		if strings.EqualFold(key, "Host") {
			req.Host = value
		}
	}
}

// stripCacheControlBody 剥掉发往上游请求体里所有 cache_control 键（递归）。
// 用于"读不回缓存的号池"渠道：避免每次建缓存付 1.25x 溢价却永远 cache_read=0。路径无关，
// 连本网关自动注入的 cache_control 也一起剥。非 JSON / 无 cache_control / 解析失败时原样返回（无害）。
func stripCacheControlBody(r io.Reader) io.Reader {
	if r == nil {
		return r
	}
	data, err := io.ReadAll(r)
	if err != nil || len(data) == 0 {
		return bytes.NewReader(data)
	}
	var v any
	if err := common2.Unmarshal(data, &v); err != nil {
		return bytes.NewReader(data)
	}
	if !removeCacheControlKeys(v) {
		return bytes.NewReader(data)
	}
	out, err := common2.Marshal(v)
	if err != nil {
		return bytes.NewReader(data)
	}
	return bytes.NewReader(out)
}

func removeCacheControlKeys(v any) bool {
	changed := false
	switch t := v.(type) {
	case map[string]any:
		if _, ok := t["cache_control"]; ok {
			delete(t, "cache_control")
			changed = true
		}
		for _, val := range t {
			if removeCacheControlKeys(val) {
				changed = true
			}
		}
	case []any:
		for _, val := range t {
			if removeCacheControlKeys(val) {
				changed = true
			}
		}
	}
	return changed
}

// claudeCodeMimicUserAgent 是发往自有 CC 号池时伪装的 Claude Code 客户端 UA。
// 号池(sub2api)用 `^claude-cli/\d+\.\d+\.\d+` 正则判定 Claude Code，命中后走稳定缓存路径并自行补齐
// anthropic-beta 等头。版本号随官方 CLI 升级时可调。
const claudeCodeMimicUserAgent = "claude-cli/2.1.161 (external, cli)"

// synthClaudeCodeMetadataUserID 按 new-api userId 合成一个号池可解析的合规 metadata.user_id（legacy 格式
// user_<64hex>_account_<可空>_session_<uuid>）。仅在客户端未带时用，保证号池 isClaudeCodeClient 判定通过。
func synthClaudeCodeMetadataUserID(userId int) string {
	u := uint64(userId)
	if u == 0 {
		u = 1
	}
	device := fmt.Sprintf("%064x", u)
	session := fmt.Sprintf("%08x-0000-4000-8000-%012x", uint32(u), u&0xFFFFFFFFFFFF)
	return "user_" + device + "_account__session_" + session
}

// ensureClaudeCodeMetadata 确保发往号池的请求体里有 metadata.user_id（缺则按 userId 合成）。
// 客户端已带且非空则原样保留。非 JSON 对象 / 解析失败时原样返回（无害）。
func ensureClaudeCodeMetadata(r io.Reader, userId int) io.Reader {
	if r == nil {
		return r
	}
	data, err := io.ReadAll(r)
	if err != nil || len(data) == 0 {
		return bytes.NewReader(data)
	}
	var m map[string]any
	if err := common2.Unmarshal(data, &m); err != nil {
		return bytes.NewReader(data)
	}
	if md, ok := m["metadata"].(map[string]any); ok {
		if uid, ok := md["user_id"].(string); ok && strings.TrimSpace(uid) != "" {
			return bytes.NewReader(data)
		}
		md["user_id"] = synthClaudeCodeMetadataUserID(userId)
	} else {
		m["metadata"] = map[string]any{"user_id": synthClaudeCodeMetadataUserID(userId)}
	}
	out, err := common2.Marshal(m)
	if err != nil {
		return bytes.NewReader(data)
	}
	return bytes.NewReader(out)
}

func DoApiRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	// 读不回缓存的号池：剥掉 cache_control，止住无收益的建缓存溢价
	if info != nil && info.ChannelSetting.NoUpstreamCache {
		requestBody = stripCacheControlBody(requestBody)
	}
	// 自有 CC 号池：补 metadata.user_id，让号池判定为 Claude Code → 走缓存路径
	if info != nil && info.ChannelSetting.ClaudeCodeMimic {
		requestBody = ensureClaudeCodeMetadata(requestBody, info.UserId)
	}
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	if common2.DebugEnabled {
		println("fullRequestURL:", fullRequestURL)
	}

	// SmartRelay 路由：命中分组白名单且为 chat/completions 时，先经本机 smart-relay
	//（响应缓存 / 上游 prompt 缓存注入 / 压缩）。真上游 URL 放 X-SmartRelay-Upstream 头，
	// sidecar 不可达或内部错时 failsafe 直连真上游，杜绝"代理挂了全站瘫"。
	if srURL, ok := smartRelayTarget(info, fullRequestURL); ok {
		bodyBytes, rerr := io.ReadAll(requestBody)
		if rerr != nil {
			return nil, fmt.Errorf("read request body failed: %w", rerr)
		}
		req, berr := buildUpstreamRequest(a, c, info, srURL, bytes.NewReader(bodyBytes))
		if berr != nil {
			return nil, berr
		}
		req.Header.Set("X-SmartRelay-Upstream", fullRequestURL)
		req.Header.Set("X-SmartRelay-Provider-Type", smartRelayProviderType(info))
		resp, derr := doRequest(c, req, info)
		if derr == nil && !smartRelayFailed(resp) {
			captureSmartRelayHeaders(c, resp)
			return resp, nil
		}
		// failsafe：标记 sidecar 不健康 + 直连真上游重试（用缓冲的 body 重放）
		markSmartRelayUnhealthy()
		if resp != nil {
			resp.Body.Close()
		}
		common2.SysLog("smart-relay failsafe -> direct upstream")
		directReq, berr2 := buildUpstreamRequest(a, c, info, fullRequestURL, bytes.NewReader(bodyBytes))
		if berr2 != nil {
			return nil, berr2
		}
		resp2, derr2 := doRequest(c, directReq, info)
		if derr2 != nil {
			return nil, fmt.Errorf("do request failed: %w", derr2)
		}
		captureSmartRelayHeaders(c, resp2)
		return resp2, nil
	}

	req, err := buildUpstreamRequest(a, c, info, fullRequestURL, requestBody)
	if err != nil {
		return nil, err
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	captureSmartRelayHeaders(c, resp)
	return resp, nil
}

// buildUpstreamRequest 构造发往上游（或 smart-relay）的请求，统一 header 处理，
// 供直连与 SmartRelay failsafe 两条路径复用，避免逻辑漂移。
func buildUpstreamRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestURL string, body io.Reader) (*http.Request, error) {
	req, err := http.NewRequest(c.Request.Method, requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	headers := req.Header
	if err = a.SetupRequestHeader(c, &headers, info); err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	// 自有 CC 号池：强制 Claude Code 客户端 UA，让号池判定为 Claude Code（须在 header override 之后，确保生效）
	if info != nil && info.ChannelSetting.ClaudeCodeMimic {
		req.Header.Set("User-Agent", claudeCodeMimicUserAgent)
		req.Header.Set("X-App", "cli")
	}
	// 注入 new-api user_id 给 smart-relay 识别真实用户（其他上游会忽略此 header）
	if info != nil && info.UserId > 0 {
		req.Header.Set("X-New-Api-User-Id", strconv.Itoa(info.UserId))
	}
	return req, nil
}

// smartRelayUnhealthyUntil：failsafe 后短暂跳过 sidecar 的截止 unix 秒。
var smartRelayUnhealthyUntil atomic.Int64

func smartRelayHealthy() bool { return time.Now().Unix() >= smartRelayUnhealthyUntil.Load() }
func markSmartRelayUnhealthy() {
	smartRelayUnhealthyUntil.Store(time.Now().Add(30 * time.Second).Unix())
}

// smartRelayTarget 命中「开关+分组白名单+chat/completions+sidecar健康」时，
// 返回经 sidecar 的目标 URL（http://<sidecar>/upstream/dyn<原路径>）。
func smartRelayTarget(info *common.RelayInfo, fullRequestURL string) (string, bool) {
	if info == nil {
		return "", false
	}
	srs := operation_setting.GetSmartRelaySetting()
	if !srs.ShouldRoute(info.UsingGroup) {
		return "", false
	}
	if !smartRelayHealthy() {
		return "", false
	}
	u, err := url.Parse(fullRequestURL)
	if err != nil || u.Path == "" {
		return "", false
	}
	// 仅路由 chat/completions（sidecar 只优化这类；其余直连省一跳）
	if !strings.HasSuffix(strings.TrimRight(u.Path, "/"), "/chat/completions") {
		return "", false
	}
	return strings.TrimRight(srs.URL, "/") + "/upstream/dyn" + u.Path, true
}

// smartRelayProviderType 由最终请求格式映射 sidecar 优化器类型。
func smartRelayProviderType(info *common.RelayInfo) string {
	switch info.GetFinalRequestRelayFormat() {
	case types.RelayFormatClaude:
		return "anthropic"
	case types.RelayFormatGemini:
		return "gemini"
	default:
		return "openai"
	}
}

// smartRelayFailed 判定是否为 sidecar 自身故障（需 failsafe 直连）。
// sidecar 处理过的响应必带 X-SmartRelay-Status；缺该头且 5xx = sidecar 内部错，
// 而上游透传的错误码（sidecar 正常转发）会带该头，不触发 failsafe，避免对上游重复调用。
func smartRelayFailed(resp *http.Response) bool {
	if resp == nil {
		return true
	}
	return resp.Header.Get("X-SmartRelay-Status") == "" && resp.StatusCode >= 500
}

func DoFormRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	if common2.DebugEnabled {
		println("fullRequestURL:", fullRequestURL)
	}
	req, err := http.NewRequest(c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	// set form data
	req.Header.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	// 注入 new-api user_id 给 smart-relay 识别真实用户（其他上游会忽略此 header）
	if info != nil && info.UserId > 0 {
		req.Header.Set("X-New-Api-User-Id", strconv.Itoa(info.UserId))
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	captureSmartRelayHeaders(c, resp)
	return resp, nil
}

func DoWssRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*websocket.Conn, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	targetHeader := http.Header{}
	err = a.SetupRequestHeader(c, &targetHeader, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	for key, value := range headerOverride {
		targetHeader.Set(key, value)
	}
	targetHeader.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	targetConn, _, err := websocket.DefaultDialer.Dial(fullRequestURL, targetHeader)
	if err != nil {
		return nil, fmt.Errorf("dial failed to %s: %w", fullRequestURL, err)
	}
	// send request body
	//all, err := io.ReadAll(requestBody)
	//err = service.WssString(c, targetConn, string(all))
	return targetConn, nil
}

func startPingKeepAlive(c *gin.Context, pingInterval time.Duration) context.CancelFunc {
	pingerCtx, stopPinger := context.WithCancel(context.Background())

	gopool.Go(func() {
		defer func() {
			// 增加panic恢复处理
			if r := recover(); r != nil {
				if common2.DebugEnabled {
					println("SSE ping goroutine panic recovered:", fmt.Sprintf("%v", r))
				}
			}
			if common2.DebugEnabled {
				println("SSE ping goroutine stopped.")
			}
		}()

		if pingInterval <= 0 {
			pingInterval = helper.DefaultPingInterval
		}

		ticker := time.NewTicker(pingInterval)
		// 确保在任何情况下都清理ticker
		defer func() {
			ticker.Stop()
			if common2.DebugEnabled {
				println("SSE ping ticker stopped")
			}
		}()

		var pingMutex sync.Mutex
		if common2.DebugEnabled {
			println("SSE ping goroutine started")
		}

		// 增加超时控制，防止goroutine长时间运行
		maxPingDuration := 120 * time.Minute // 最大ping持续时间
		pingTimeout := time.NewTimer(maxPingDuration)
		defer pingTimeout.Stop()

		for {
			select {
			// 发送 ping 数据
			case <-ticker.C:
				if err := sendPingData(c, &pingMutex); err != nil {
					if common2.DebugEnabled {
						println("SSE ping error, stopping goroutine:", err.Error())
					}
					return
				}
			// 收到退出信号
			case <-pingerCtx.Done():
				return
			// request 结束
			case <-c.Request.Context().Done():
				return
			// 超时保护，防止goroutine无限运行
			case <-pingTimeout.C:
				if common2.DebugEnabled {
					println("SSE ping goroutine timeout, stopping")
				}
				return
			}
		}
	})

	return stopPinger
}

func sendPingData(c *gin.Context, mutex *sync.Mutex) error {
	// 增加超时控制，防止锁死等待
	done := make(chan error, 1)
	go func() {
		mutex.Lock()
		defer mutex.Unlock()

		err := helper.PingData(c)
		if err != nil {
			logger.LogError(c, "SSE ping error: "+err.Error())
			done <- err
			return
		}

		if common2.DebugEnabled {
			println("SSE ping data sent.")
		}
		done <- nil
	}()

	// 设置发送ping数据的超时时间
	select {
	case err := <-done:
		return err
	case <-time.After(10 * time.Second):
		return errors.New("SSE ping data send timeout")
	case <-c.Request.Context().Done():
		return errors.New("request context cancelled during ping")
	}
}

func DoRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	return doRequest(c, req, info)
}
func doRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	var client *http.Client
	var err error
	if info.ChannelSetting.Proxy != "" {
		client, err = service.NewProxyHttpClient(info.ChannelSetting.Proxy)
		if err != nil {
			return nil, fmt.Errorf("new proxy http client failed: %w", err)
		}
	} else {
		client = service.GetHttpClient()
	}

	var stopPinger context.CancelFunc
	if info.IsStream {
		helper.SetEventStreamHeaders(c)
		// 处理流式请求的 ping 保活
		generalSettings := operation_setting.GetGeneralSetting()
		if generalSettings.PingIntervalEnabled && !info.DisablePing {
			pingInterval := time.Duration(generalSettings.PingIntervalSeconds) * time.Second
			stopPinger = startPingKeepAlive(c, pingInterval)
			// 使用defer确保在任何情况下都能停止ping goroutine
			defer func() {
				if stopPinger != nil {
					stopPinger()
					if common2.DebugEnabled {
						println("SSE ping goroutine stopped by defer")
					}
				}
			}()
		}
	}

	resp, err := client.Do(req)
	if err != nil {
		logger.LogError(c, "do request failed: "+err.Error())
		return nil, types.NewError(err, types.ErrorCodeDoRequestFailed, types.ErrOptionWithHideErrMsg("upstream error: do request failed"))
	}
	if resp == nil {
		return nil, errors.New("resp is nil")
	}

	_ = req.Body.Close()
	_ = c.Request.Body.Close()
	return resp, nil
}

func DoTaskApiRequest(a TaskAdaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.BuildRequestURL(info)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest(c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	req.GetBody = func() (io.ReadCloser, error) {
		return io.NopCloser(requestBody), nil
	}

	err = a.BuildRequestHeader(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	captureSmartRelayHeaders(c, resp)
	return resp, nil
}

// captureSmartRelayHeaders 把 SmartRelay 上游返回的优化指标暂存到 gin context，
// 后续 GenerateTextOtherInfo 会把它写入 log.Other，供前端展示节省量与缓存命中。
func captureSmartRelayHeaders(c *gin.Context, resp *http.Response) {
	if c == nil || resp == nil {
		return
	}
	saved := resp.Header.Get("X-SmartRelay-Tokens-Saved")
	if saved == "" {
		return
	}
	n, err := strconv.Atoi(strings.TrimSpace(saved))
	if err != nil || n == 0 {
		// 缓存命中也可能是 0 saved，但我们仍记录 cache hit 标志
		hit := resp.Header.Get("X-SmartRelay-Cache-Hit")
		if hit != "true" {
			return
		}
	}
	c.Set("smartrelay_tokens_saved", n)
	if t := resp.Header.Get("X-SmartRelay-Save-Type"); t != "" {
		c.Set("smartrelay_save_type", t)
	}
	if h := resp.Header.Get("X-SmartRelay-Cache-Hit"); h != "" {
		c.Set("smartrelay_cache_hit", h == "true")
	}
}
